version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "4000:8080"
    depends_on:
      - fluentd
    networks:
        - test_net
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: docker

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    networks:
        - test_net
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.6.1
    expose:
      - 9200
    networks:
        - test_net
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.6.1
    links:
      - "elasticsearch"
    networks:
        - test_net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
networks:
  test_net:
    driver: bridge
